---
title: "IG4 - Visualisation"
subtitle: "Descriptives statistics"
author: "Paul Bastide, Chloé Serre-Combe, Alexandre Capel"
output:
  ioslides_presentation:
    fig_width: 7
    fig_height: 4
  self_contained: true
---

<!-- ************************************************************************ -->
# Statistics
<!-- ************************************************************************ -->

## Goal {.build}

<center>
*Study of features of a* **population**  
$~$
</center>

1. All the french people
2. All tax units
3. all the trees from a forest
4. All the arable area

<center>
*from a* **sample**.  
$~$
</center>

1. Survey of some random people
2. Tax control
3. Some random trees
4. Survey of farmer

## Définitions {.build}

**Individual**: *statistic unit from the study*

$\hookrightarrow$ a tree

**Population**: *a set of all the indivudal involved by the study*

$\hookrightarrow$ Fontainebleau's forest

**Sample**: *subset of the population*

$\hookrightarrow$ felled trees

**Size**  of the saple: *number of individual in the sample*

$\hookrightarrow$ nomber of felled tree

## Examples {.build}

**Individu**: a french  
**Population**: all the french 
**Sample**: IPSOS survey
**Size**: 10000  

**Individual**: a tax unit
**Population**: all the tax unit  
**Sample**: checked tax unit 
**Size**: 1000  

**Individual**: farm plot 
**Population**: all the arable area of Occitanie
**Sample**: my garden  
**Size**: 1  

## Questions {.build}

$\rightarrow$  we ask a **question** about the population.

$\rightarrow$ we respond by measuring a **variable** on the individuals in the sample.

## Examples {.build}

How many children do the french people have ?

**Individu**: a french  
**Population**: all the french 
**Sample**: IPSOS survey
**Size**: 10000  
**Variable**: number of children

Hox mush do the french people pay for the outcome tax ?

**Individual**: a tax unit
**Population**: all the tax unit  
**Sample**: checked tax unit 
**Size**: 1000  
**Variable**: the money given to the administration

## Examples {.build}

Are the trees from the Fontainebleau's forest in godd health ?

**Individual**: a tree 
**Population**: Fontainebleau's forest  
**Sample**: felled tree
**Size**: 100  
**Variable**: tree's health  

What is the orientation of agricultural plots?

**Individual**: farm plot 
**Population**: all the arable area of Occitanie
**Sample**: my garden  
**Size**: 1  
**Variable**: orientation

## Variable and modality {.build}

**Variable**: some measurable feature

**Modality**: possible value of the variable

## Exemples {.build}

**Variable**: number of children
**Modality**: an integer

**Variable**: money paid to the administration
**Values**: a positive number

**Variable**: tree's health   
**Modality**: bad, mid, good, excellent

**Variable**: orientation  
**Modality**: North, South, East, West

## Variable et modality

**Variable**: some measurable feature

**Modality**: possible value of the variable

**Warning**: the modalities must be :

* *incompatible* all the response of an individual must belong to only one modality;
* *exhaustive* : toutes les situations possibles doivent être prévues ;
* *without ambiguity* : avoid classification error.

## Qualitative and quantitative variables {.build}

* **Qualitative** the modalities are **words**.

  - **ordinal**: scale between the categories
  - **nominal**: no order relationship between the categories.

$~$  
$~$

* **Quantitative**the modalities are **numbers**.

  - **discrete**: "isolated" number (integer)
  - **continuous**: real values 
  
## Examples

**Variable**: number of child; $\qquad$ **Modality**: an integer 

>* $\to$ quantitative, discrete

**Variable**:money paid to the administration 
**Value**: a positive number

>* $\to$ quantitative, continu

**Variable**: tree's health  
**Modality**: bad, mid, good, excellent

>* $\to$ qualitative, ordinal

**Variable**: orientation; $\qquad$ **Modality**: North, South, East, West

>* $\to$ qualitative, nominal
  
## Statistical approach {.build}

1 - We ask a question to the population.

*How old are the people from Montpellier ?*

2 - We define a variable.

*age (variable quantitative continuous)*

3 - We choose a sample.

*survey of 1000 random montpellierian*

4 - We measure the variable on the individual from the sample.

*"Hi, it's for a survey, how old are you ?"*

5 - and then ?
